In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/nehalbirla/motorcycle-dataset/BIKE DETAILS.csv


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [3]:
df=pd.read_csv("/kaggle/input/datasets/nehalbirla/motorcycle-dataset/BIKE DETAILS.csv")

In [4]:
df.head()

,name,selling_price,year,seller_type,owner,km_driven,ex_showroom_price
0,Royal Enfield Classic 350,175000,2019,Individual,1st owner,350,NaN
1,Honda Dio,45000,2017,Individual,1st owner,5650,NaN
2,Royal Enfield Classic Gunmetal Grey,150000,2018,Individual,1st owner,12000,148114.0
3,Yamaha Fazer FI V 2.0 [2016-2018],65000,2015,Individual,1st owner,23000,89643.0
4,Yamaha SZ [2013-2014],20000,2011,Individual,2nd owner,21000,NaN


In [5]:
df.shape


(1061, 7)

In [6]:
df.isnull().sum()

name                   0
selling_price          0
year                   0
seller_type            0
owner                  0
km_driven              0
ex_showroom_price    435
dtype: int64

In [7]:
df.dropna(subset=['ex_showroom_price'],inplace=True)

In [8]:
df.head()

,name,selling_price,year,seller_type,owner,km_driven,ex_showroom_price
2,Royal Enfield Classic Gunmetal Grey,150000,2018,Individual,1st owner,12000,148114.0
3,Yamaha Fazer FI V 2.0 [2016-2018],65000,2015,Individual,1st owner,23000,89643.0
5,Honda CB Twister,18000,2010,Individual,1st owner,60000,53857.0
6,Honda CB Hornet 160R,78500,2018,Individual,1st owner,17000,87719.0
9,Bajaj Discover 125,50000,2016,Individual,1st owner,42000,60122.0


In [9]:
df.shape

(626, 7)

In [10]:
df.describe()

,selling_price,year,km_driven,ex_showroom_price
count,626.000000,626.000000,626.000000,6.260000e+02
mean,59445.164537,2014.800319,32671.576677,8.795871e+04
std,59904.350888,3.018885,45479.661039,7.749659e+04
min,6000.000000,2001.000000,380.000000,3.049000e+04
25%,30000.000000,2013.000000,13031.250000,5.485200e+04
50%,45000.000000,2015.000000,25000.000000,7.275250e+04
75%,65000.000000,2017.000000,40000.000000,8.703150e+04
max,760000.000000,2020.000000,585659.000000,1.278000e+06


In [11]:
from sklearn.preprocessing import LabelEncoder


In [12]:
le=LabelEncoder()

In [13]:
df['seller_type']=le.fit_transform(df['seller_type'])

In [14]:
df['owner']=le.fit_transform(df['owner'])

In [15]:
df.head()

,name,selling_price,year,seller_type,owner,km_driven,ex_showroom_price
2,Royal Enfield Classic Gunmetal Grey,150000,2018,1,0,12000,148114.0
3,Yamaha Fazer FI V 2.0 [2016-2018],65000,2015,1,0,23000,89643.0
5,Honda CB Twister,18000,2010,1,0,60000,53857.0
6,Honda CB Hornet 160R,78500,2018,1,0,17000,87719.0
9,Bajaj Discover 125,50000,2016,1,0,42000,60122.0


In [16]:
df['brand']=df['name'].str.split().str.get(0)

In [17]:
df['brand']=le.fit_transform(df['brand'])

In [18]:
df.head()

,name,selling_price,year,seller_type,owner,km_driven,ex_showroom_price,brand
2,Royal Enfield Classic Gunmetal Grey,150000,2018,1,0,12000,148114.0,11
3,Yamaha Fazer FI V 2.0 [2016-2018],65000,2015,1,0,23000,89643.0,16
5,Honda CB Twister,18000,2010,1,0,60000,53857.0,6
6,Honda CB Hornet 160R,78500,2018,1,0,17000,87719.0,6
9,Bajaj Discover 125,50000,2016,1,0,42000,60122.0,2


In [19]:
df.drop(['name'],axis=1,inplace=True)

In [20]:
df.head()

,selling_price,year,seller_type,owner,km_driven,ex_showroom_price,brand
2,150000,2018,1,0,12000,148114.0,11
3,65000,2015,1,0,23000,89643.0,16
5,18000,2010,1,0,60000,53857.0,6
6,78500,2018,1,0,17000,87719.0,6
9,50000,2016,1,0,42000,60122.0,2


In [21]:
X=df.drop('selling_price',axis=1)
y=df['selling_price']

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [24]:
from sklearn.preprocessing import StandardScaler

In [25]:
scaler=StandardScaler()

In [26]:
X_train_scaled=scaler.fit_transform(X_train)

In [27]:
X_test_scaled=scaler.transform(X_test)

In [28]:
X_train_scaled

array([[-0.5749005 ,  0.0776931 , -0.34757978,  0.13923465, -0.20319716,
        -0.24227585],
       [ 0.41859115,  0.0776931 ,  2.36788725, -0.56050753, -0.6635474 ,
        -0.24227585],
       [ 0.41859115,  0.0776931 , -0.34757978, -0.6604707 , -0.53841522,
        -0.24227585],
       ...,
       [-0.5749005 ,  0.0776931 , -0.34757978, -0.08568248, -0.512163  ,
        -0.24227585],
       [ 1.4120828 ,  0.0776931 , -0.34757978, -0.59799372,  0.36211088,
        -0.45554684],
       [-0.24373662,  0.0776931 , -0.34757978,  0.21420702, -0.61226874,
        -0.24227585]])

In [29]:
X_test_scaled

array([[ 7.49755031e-01,  7.76930969e-02, -3.47579780e-01,
         6.42622724e-02, -4.65191610e-01, -1.09535981e+00],
       [ 8.74272651e-02,  7.76930969e-02,  2.36788725e+00,
        -6.85461490e-01,  1.75495977e+00,  8.24079109e-01],
       [ 7.49755031e-01,  7.76930969e-02, -3.47579780e-01,
         6.42622724e-02, -6.12047422e-01, -4.55546837e-01],
       [-2.43736618e-01,  7.76930969e-02, -3.47579780e-01,
        -4.73039757e-01, -8.03973770e-02,  1.89043406e+00],
       [-9.06064384e-01,  7.76930969e-02, -3.47579780e-01,
        -8.56824800e-02, -6.12268745e-01, -2.42275846e-01],
       [-1.23722827e+00,  7.76930969e-02, -3.47579780e-01,
        -1.10673272e-01, -6.12268745e-01, -2.42275846e-01],
       [ 1.41208280e+00,  7.76930969e-02, -3.47579780e-01,
        -7.40441232e-01,  1.13349265e+01,  1.03735010e+00],
       [-2.23071992e+00,  7.76930969e-02, -3.47579780e-01,
         5.64078114e-01, -2.07595485e-02, -1.09535981e+00],
       [ 1.41208280e+00,  7.76930969e-02, -3.475

In [30]:
df.head()

,selling_price,year,seller_type,owner,km_driven,ex_showroom_price,brand
2,150000,2018,1,0,12000,148114.0,11
3,65000,2015,1,0,23000,89643.0,16
5,18000,2010,1,0,60000,53857.0,6
6,78500,2018,1,0,17000,87719.0,6
9,50000,2016,1,0,42000,60122.0,2


In [31]:
from xgboost import XGBRegressor
from sklearn.metrics import r2_score,mean_absolute_error


In [32]:
xgb_model=XGBRegressor(n_estimators=100,learning_rate=0.1,max_depth=5,random_state=42)

In [33]:
xgb_model.fit(X_train_scaled,y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.1, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=100,
             n_jobs=None, num_parallel_tree=None, ...)

In [34]:
y_pred=xgb_model.predict(X_test_scaled)

In [35]:
y_pred

array([ 39271.61 , 159942.25 ,  32154.994,  51414.477,  26321.164,
        22961.967, 405793.88 ,  24426.094, 166777.66 ,  45422.14 ,
       135456.3  ,  50414.965,  19388.906,  41412.914,  89411.67 ,
        43775.95 ,  20618.934,  50171.887,  36055.363,  94704.766,
        61497.234,  69378.06 ,  60605.836,  23177.168,  31713.266,
        30193.174,  36338.17 ,  72388.836,  23901.244,  37900.887,
        31942.574,  16043.892,  49649.383,  87248.95 ,  35104.117,
        25806.84 , 120149.45 ,  35577.934,  41405.438,  35072.438,
        22146.957,  43163.32 ,  60210.484,  31462.707,  34476.55 ,
        64725.23 ,  38345.39 ,  22469.604, 367998.66 ,  67103.82 ,
        88898.79 ,  59184.7  ,  54724.645,  49830.53 ,  53954.32 ,
        39531.566,  41818.742,  18372.139,  24352.336,  29466.938,
        50796.88 , 136252.11 ,  33921.613,  37482.992,  47111.305,
        47374.273,  24981.758,  50972.04 , 134728.44 ,  32801.734,
        57723.34 , 141369.56 ,  41563.777, 141251.05 , 137605.

In [36]:
y_test

816      45000
890     185000
392      45000
386      35000
878      35000
         ...  
627     120000
409     140000
1041     30000
352      50000
722      15000
Name: selling_price, Length: 126, dtype: int64

In [37]:
r2=r2_score(y_test,y_pred)

In [38]:
r2

0.7410446405410767

In [39]:
mae=mean_absolute_error(y_test,y_pred)

In [40]:
mae

14679.923828125

In [42]:
import pickle
pickle.dump(xgb_model, open('bike_model.pkl','wb'))
pickle.dump(scaler, open('scaler.pkl','wb'))